import os
import requests
from flask import Flask, request, jsonify
from datetime import datetime

app = Flask(__name__)

TOKEN = os.environ.get("WHATSAPP_TOKEN")
PHONE_NUMBER_ID = os.environ.get("PHONE_NUMBER_ID")
VERIFY_TOKEN = os.environ.get("VERIFY_TOKEN", "botrdv2024")

COIFFEURS = {"1": "Youssef", "2": "Karim", "3": "Hassan"}
HORAIRES = ["09:00","09:30","10:00","10:30","11:00","11:30","14:00","14:30","15:00","15:30","16:00","16:30","17:00"]

rdv_list = []
sessions = {}

def send_message(to, message):
    url = f"https://graph.facebook.com/v18.0/{PHONE_NUMBER_ID}/messages"
        headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
            data = {"messaging_product": "whatsapp", "to": to, "type": "text", "text": {"body": message}}
                requests.post(url, headers=headers, json=data)

                def get_horaires_dispo(coiffeur, date):
                    pris = [r["heure"] for r in rdv_list if r["coiffeur"] == coiffeur and r["date"] == date]
                        return [h for h in HORAIRES if h not in pris]

                        def traiter_message(phone, message):
                            msg = message.strip().lower()
                                session = sessions.get(phone, {"etape": "debut"})
                                    if msg in ["rdv", "bonjour", "salut", "reservation"]:
                                            sessions[phone] = {"etape": "choix_coiffeur"}
                                                    liste = "\n".join([f"{k}. {v}" for k, v in COIFFEURS.items()])
                                                            send_message(phone, f"Bonjour ! Choisissez votre coiffeur :\n{liste}")
                                                                    return
                                                                        etape = session.get("etape", "debut")
                                                                            if etape == "choix_coiffeur":
                                                                                    if msg in COIFFEURS:
                                                                                                session["coiffeur"] = COIFFEURS[msg]
                                                                                                            session["etape"] = "choix_jour"
                                                                                                                        sessions[phone] = session
                                                                                                                                    send_message(phone, f"Coiffeur: {COIFFEURS[msg]}\nQuel jour ? (format: 2024-12-25)")
                                                                                                                                            else:
                                                                                                                                                        send_message(phone, "Choisissez 1, 2 ou 3.")
                                                                                                                                                            elif etape == "choix_jour":
                                                                                                                                                                    try:
                                                                                                                                                                                datetime.strptime(msg, "%Y-%m-%d")
                                                                                                                                                                                            session["date"] = msg
                                                                                                                                                                                                        dispos = get_horaires_dispo(session["coiffeur"], msg)
                                                                                                                                                                                                                    if not dispos:
                                                                                                                                                                                                                                    send_message(phone, "Aucun creneau disponible. Choisissez une autre date.")
                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                session["etape"] = "choix_heure"
                                                                                                                                                                                                                                                                                session["dispos"] = dispos
                                                                                                                                                                                                                                                                                                sessions[phone] = session
                                                                                                                                                                                                                                                                                                                liste_h = "\n".join([f"{i+1}. {h}" for i, h in enumerate(dispos)])
                                                                                                                                                                                                                                                                                                                                send_message(phone, f"Creneaux le {msg} :\n{liste_h}\nEntrez le numero.")
                                                                                                                                                                                                                                                                                                                                        except:
                                                                                                                                                                                                                                                                                                                                                    send_message(phone, "Format invalide. Ex: 2024-12-25")
                                                                                                                                                                                                                                                                                                                                                        elif etape == "choix_heure":
                                                                                                                                                                                                                                                                                                                                                                dispos = session.get("dispos", [])
                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                    idx = int(msg) - 1
                                                                                                                                                                                                                                                                                                                                                                                                if 0 <= idx < len(dispos):
                                                                                                                                                                                                                                                                                                                                                                                                                session["heure"] = dispos[idx]
                                                                                                                                                                                                                                                                                                                                                                                                                                session["etape"] = "confirmation"
                                                                                                                                                                                                                                                                                                                                                                                                                                                sessions[phone] = session
                                                                                                                                                                                                                                                                                                                                                                                                                                                                send_message(phone, f"Confirmer ?\nCoiffeur: {session['coiffeur']}\nDate: {session['date']}\nHeure: {dispos[idx]}\nRepondez OUI")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            send_message(phone, "Numero invalide.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                send_message(phone, "Entrez le numero du creneau.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif etape == "confirmation":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if msg == "oui":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rdv = {"phone": phone, "coiffeur": session["coiffeur"], "date": session["date"], "heure": session["heure"], "statut": "confirme"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rdv_list.append(rdv)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del sessions[phone]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            send_message(phone, f"RDV confirme !\n{rdv['coiffeur']} - {rdv['date']} - {rdv['heure']}\nA bientot !")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del sessions[phone]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            send_message(phone, "RDV annule. Tapez RDV pour recommencer.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        send_message(phone, "Tapez RDV pour prendre rendez-vous.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.route("/webhook", methods=["GET"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def verify():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mode = request.args.get("hub.mode")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                token = request.args.get("hub.verify_token")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    challenge = request.args.get("hub.challenge")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if mode == "subscribe" and token == VERIFY_TOKEN:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return challenge, 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return "Forbidden", 403
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route("/webhook", methods=["POST"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def webhook():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data = request.get_json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    msg = data["entry"][0]["changes"][0]["value"]["messages"][0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            traiter_message(msg["from"], msg["text"]["body"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Erreur: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return jsonify({"status": "ok"}), 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.route("/rdvs")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def get_rdvs():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonify(rdv_list), 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route("/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def home():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return "Bot RDV actif !", 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)))
